version: '2'

services:

    mysqlv8:

        image: mysql:8.0.21
        hostname: mysqlv8
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root


        ports:
          - 3306:3306
          - 33060:33060

        volumes:

          - ../EB-NFS/data/mysqlv8:/var/lib/mysql
          - ../EB-NFS:/var/nfs
          - ./docker/mysql8.0/conf.d:/etc/mysql/conf.d
          - ./log/mysql8.0:/var/log/mysql


        networks:
            - development.local.network

    mailcatcher:
       hostname: mailcatcher
       restart: always
       image: dockage/mailcatcher:0.6.5
       ports:
         - 1085:1080
       networks:
           - development.local.network

    adminer:
       hostname: adminer
       image: adminer:latest
       restart: always
       ports:
         - 8099:8080
       networks:
           - development.local.network

    docker-redis:
       image: redis
       restart: always
       hostname: docker-redis
       ports:
         - 6379:6379
       environment:
            - REDIS_PASSWORD=dockerredispassword
       command: redis-server /usr/local/etc/redis/redis.conf
       volumes:
         - ./docker/Redis/redis.conf:/usr/local/etc/redis/redis.conf:cached
         - ./data/redis:/data:cached
         - ./data/redis:/tmp:cached
         - ./log/redis:/var/log/redis:cached

       networks:
           - development.local.network

networks:
    development.local.network:
        driver: bridge
        
